"""add updated_at to payroll

Revision ID: 139331d4a815
Revises: 9dc168a98e88
Create Date: 2026-09-08 12:38:46.890331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139331d4a815'
down_revision = '9dc168a98e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'updated_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.text('CURRENT_TIMESTAMP')
            )
        )

        batch_op.alter_column('present_days',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('absent_days',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('payable_days',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_payroll_employee_period'), type_='unique')
        batch_op.create_unique_constraint('uq_employee_payroll_period', ['employee_id', 'month', 'year'])
        batch_op.drop_constraint(batch_op.f('payroll_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payroll_employee_id_fkey'), 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_employee_payroll_period', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_payroll_employee_period'), ['employee_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('payable_days',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('absent_days',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('present_days',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
