"""add payroll payment fields

Revision ID: 42520fc58169
Revises: 49a5e5f08286
Create Date: 2026-09-10 15:27:24.744837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42520fc58169'
down_revision = '49a5e5f08286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
