"""support decimal payroll attendance days

Revision ID: 9dc168a98e88
Revises: 5b5e4822a93d
Create Date: 2026-09-07 13:03:34.511911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc168a98e88'
down_revision = '5b5e4822a93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.alter_column('present_days',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('absent_days',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('payable_days',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.alter_column('payable_days',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
        batch_op.alter_column('absent_days',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
        batch_op.alter_column('present_days',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
