"""add employee salary and account number

Revision ID: bf7491117e95
Revises: 139331d4a815
Create Date: 2026-09-09 12:02:28.273919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7491117e95'
down_revision = '139331d4a815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('account_number')
        batch_op.drop_column('basic_salary')

    # ### end Alembic commands ###
