"""Add cascade delete to employee records

Revision ID: d937d3350d66
Revises: 067845007310
Create Date: 2026-08-31 12:47:11.143109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd937d3350d66'
down_revision = '067845007310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('leaves_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payroll_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payroll_employee_id_fkey'), 'employees', ['employee_id'], ['id'])

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leaves_employee_id_fkey'), 'employees', ['employee_id'], ['id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_employee_id_fkey'), 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###
